on: [push]

jobs:
  create_shipa_app:
    runs-on: ubuntu-latest
    name: Create shipa app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Shipa App Action
        uses: rostislavgit/shipa-create-app-action@v0.1.1
        env:
          SHIPA_TOKEN: ${{ secrets.SHIPA_TOKEN }}
          SHIPA_HOST: ${{ secrets.SHIPA_HOST }}
        with:
          shipa-action: './infra/cluster-def.yml'
