on: [push]

jobs:
  create_shipa_app:
    runs-on: ubuntu-latest
    name: Create shipa app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Shipa App Action
        uses: rostislavgit/shipa-create-app-action@v0.0.2
        env:
          SHIPA_TOKEN: ${{ secrets.SHIPA_TOKEN }}
          SHIPA_HOST: ${{ secrets.SHIPA_HOST }}
        with:
          app: './example/app.yml'
#          shipa-action: './example/shipa-action.yml'
